# Generated by Django 4.0.5 on 2022-07-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_vehiculo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='patente',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
